### ISSUE TITLE
Every time I open up a new page or block in the sidebar, it resets the resizings I've done with everything else in the sidebar 🙁️

### ISSUE THREAD

**Issue by classicrob** [GitMurf/masonry-vanilla#2]

**Comment by GitMurf** [comment]
@classicrob yep unfortunately that is a Roam thing. They basically reset/reload all the pages each time because they add the newly opened page/block to the very first position (very left). Preferably they would just insert the new DIV to leave the other stuff alone, but instead they essentially "wipe out" the pages in the sidebar and re-render them which means you lose all the sizing etc. I have pushed them to change this but you have a louder voice than me ;) So wouldn't hurt if you request this change from Bardia / Conor et al.

**Comment by GitMurf** [comment]
I'll leave this issue "open" to track it but it will require Roam to change things on their end to make work.

**Comment by classicrob** [comment]
Noted. I'll bring it up at some point.

**Comment by classicrob** [comment]
I've been using mainly Stylus for CSS stuff and just checked switching to roam/css to see if Stylus was the issue, but that didn't fix it.
